### ISSUE TITLE
merchantOrderId field length limited to 24 characters

### ISSUE THREAD

**Issue by geertdoornbos** [rabobank-nederland/omnikassa-sdk-doc#7]
Looking at the schema for the [order announce call](https://developer-sandbox.rabobank.nl/product/54975/api/54972#/RaboSmartPayOnlinePaymentAPI_1016/operation/%2Forder%2Fserver%2Fapi%2Fv2%2Forder/post), the description of the **merchantOrderId** mentioned some strange behavior for this property. It looks like the specification changes dynamically depending on another property called **shopperBankstatementReference**.
Searching on github, I found this 'java only' code:

```        /**
         * @param merchantOrderId | Must not be `null`
         *                        | - if shopperBankstatementReference is supplied:
         *                        |   Allows all ascii characters up to a length of 255 characters, if the ID contains more than 255 characters, the extra characters are removed after the 255th character.
         *                        | - else:
         *                        |   Must adhere to the pattern: '[A-Za-z0-9]{1,24}', if the ID contains more than 24 characters, the extra characters are removed after the 24th character.
         * @return Builder
         */
        public Builder withMerchantOrderId(String merchantOrderId) {
            this.merchantOrderId = merchantOrderId;
            return this;
        }
```

Schema description of shopperBankstatementReference: 
_Generated by the webshop. The value of this field must be unique when offering Riverty/AfterPay as a payment brand to the customer. If the ID contains more than 24 characters, the extra characters are removed after the 24th character._

When shopperBankstatementReference has a value, the merchantOrderId property suddenly is allowed to contain 255 characters? That is strange behavior.

It's very common to use GUID's as a way to create unique ID's. A string representation of a GUID needs at least 32 characters (leaving out braces and hyphens). So, GUID's can't be used as a **merchantOrderId**. 

The 'shopperBankstatementReference' change has been made recently. Apparently Java only, and not for .NET, PHP and sdk documentation. Is it a trial feature?

Question: is it possible to change the API to always have 255 characters for the **merchantOrderId**? Or at least 32?

**Comment by wvdiepen** [comment]
Hi Geert,
The .NET and PHP changes are always a little behind with the Java changes. (Due to internal processes)
So that is normal.
For the strangeness, this change is done for the backwards compatibility for applications that are build on an older version of the API. 
For your question, at the moment it's not possible to change it to at least 32, that's due to some restrictions we have in the api's we are currently using. When changes occur there we try to reflect that in our code, but for now unfortunately we can't.

With kind regards
